# Generated by Django 3.2.16 on 2022-10-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('altered_img', models.ImageField(upload_to='images')),
                ('url', models.CharField(default='none', max_length=128)),
                ('duplicate_url', models.CharField(default='none', max_length=128)),
                ('filename', models.CharField(default='none', max_length=128)),
                ('height', models.IntegerField(default=100)),
                ('width', models.IntegerField(default=100)),
                ('file_type', models.CharField(max_length=32)),
            ],
        ),
    ]
