# Generated by Django 3.2.15 on 2022-10-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogimage',
            name='file_type',
            field=models.CharField(default='None', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogimage',
            name='filename',
            field=models.CharField(default='None', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogimage',
            name='height',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogimage',
            name='url',
            field=models.CharField(default='www.doggo.com', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogimage',
            name='width',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DuplicateDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('url', models.CharField(max_length=128)),
                ('filename', models.CharField(max_length=128)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('file_type', models.CharField(max_length=32)),
                ('original_dog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggos.dogimage')),
            ],
        ),
    ]
