# Generated by Django 3.2.15 on 2022-10-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggos', '0002_auto_20221002_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogimage',
            name='filename',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AlterField(
            model_name='dogimage',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='dogimage',
            name='url',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AlterField(
            model_name='dogimage',
            name='width',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='duplicatedog',
            name='file_type',
            field=models.CharField(default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='duplicatedog',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='duplicatedog',
            name='url',
            field=models.CharField(default='nond', max_length=128),
        ),
        migrations.AlterField(
            model_name='duplicatedog',
            name='width',
            field=models.IntegerField(default=100),
        ),
    ]
