# Generated by Django 3.2.15 on 2022-10-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggos', '0003_auto_20221002_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogimage',
            name='img',
        ),
        migrations.AddField(
            model_name='dogimage',
            name='duplicate_url',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.DeleteModel(
            name='DuplicateDog',
        ),
    ]
