# Generated by Django 3.2.16 on 2022-10-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_alter_key_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(error_messages={'invalid': 'Resource already exists'}, max_length=64, unique=True),
        ),
    ]
